import type { TimedLyricLine } from '@/types';

/** Synced lyrics — { t: secondsFromStart, text } — from project/data.jsx */
export const LYRICS_LANTERN: TimedLyricLine[] = [
  { t: 0,    text: '[Verse 1]' },
  { t: 4,    text: 'Tape hiss, headlights, low' },
  { t: 9,    text: 'we drift the tunnel slow' },
  { t: 14,   text: 'lantern fields at three' },
  { t: 19,   text: 'mile markers blurring by' },
  { t: 24,   text: '' },
  { t: 26,   text: '[Pre]' },
  { t: 28,   text: "you said, don't fall asleep" },
  { t: 33,   text: "the radio's on repeat" },
  { t: 38,   text: '' },
  { t: 40,   text: '[Chorus]' },
  { t: 42,   text: "and it's cold, and it's quiet," },
  { t: 47,   text: "and the windshield's wet with light" },
  { t: 52,   text: 'we are nowhere, we are night' },
  { t: 57,   text: 'lantern fields at three a.m.' },
  { t: 63,   text: '' },
  { t: 65,   text: '[Verse 2]' },
  { t: 68,   text: 'your hand on the dashboard glow' },
  { t: 73,   text: "exit signs we don't know" },
  { t: 78,   text: 'tape rewinds, side B' },
  { t: 83,   text: 'an old song, half asleep' },
  { t: 88,   text: '' },
  { t: 90,   text: '[Bridge]' },
  { t: 92,   text: 'the dotted line keeps going' },
  { t: 97,   text: 'wherever you are going' },
  { t: 102,  text: "I'll be one mile behind" },
  { t: 107,  text: 'with the tape hiss, with the night' },
  { t: 113,  text: '' },
  { t: 115,  text: '[Chorus]' },
  { t: 117,  text: "and it's cold, and it's quiet," },
  { t: 122,  text: "and the windshield's wet with light" },
  { t: 127,  text: 'we are nowhere, we are night' },
  { t: 132,  text: 'lantern fields at three a.m.' },
  { t: 138,  text: '' },
  { t: 140,  text: '[Outro]' },
  { t: 142,  text: 'lantern fields, lantern fields' },
  { t: 147,  text: 'lantern fields at three' },
  { t: 156,  text: '...three a.m.' },
];

export const LYRICS_PAPER_KITES: TimedLyricLine[] = [
  { t: 0,   text: '[Verse]' },
  { t: 5,   text: 'paper kites over Gowanus' },
  { t: 11,  text: 'wires on the rooftop hum' },
  { t: 17,  text: "you said summer wouldn't end" },
  { t: 23,  text: 'it ended anyway, my friend' },
  { t: 30,  text: '' },
  { t: 32,  text: '[Chorus]' },
  { t: 34,  text: 'and the light goes / the light goes' },
  { t: 41,  text: 'all gold, all gold, all slow' },
  { t: 49,  text: "and we're cheap film, cheap film" },
  { t: 56,  text: 'burning out in the window' },
  { t: 64,  text: '' },
  { t: 70,  text: '[Verse]' },
  { t: 73,  text: "third floor, the fan won't sleep" },
  { t: 79,  text: 'the wallpaper sighs, repeats' },
  { t: 85,  text: 'you traced rivers on my wrist' },
  { t: 91,  text: "named them after streets we'd missed" },
  { t: 100, text: '' },
  { t: 105, text: '[Chorus]' },
  { t: 107, text: 'and the light goes / the light goes' },
  { t: 114, text: 'all gold, all gold, all slow' },
  { t: 122, text: "and we're cheap film, cheap film" },
  { t: 129, text: 'burning out in the window' },
  { t: 138, text: '' },
  { t: 145, text: '[Bridge]' },
  { t: 148, text: 'if a kite is just a string' },
  { t: 154, text: "and a hand that won't let go" },
  { t: 161, text: "then I'm holding, I'm holding" },
  { t: 168, text: "I'm holding, even slow" },
  { t: 180, text: '' },
  { t: 188, text: '[Outro]' },
  { t: 192, text: 'the light goes' },
  { t: 200, text: 'the light goes' },
  { t: 210, text: 'the light goes' },
];

export const LYRICS_PORCHLIGHT: TimedLyricLine[] = [
  { t: 0,   text: '[Verse 1]' },
  { t: 4,   text: 'porchlight burning, Alabama' },
  { t: 11,  text: 'moths against the screen' },
  { t: 18,  text: 'my mother singing softly' },
  { t: 25,  text: "a song she'd never been" },
  { t: 33,  text: '' },
  { t: 36,  text: '[Chorus]' },
  { t: 39,  text: 'carry me home, carry me home' },
  { t: 46,  text: 'down the long red road' },
  { t: 53,  text: 'porchlight burning, porchlight burning' },
  { t: 61,  text: 'wherever you go' },
  { t: 70,  text: '' },
  { t: 75,  text: '[Verse 2]' },
  { t: 78,  text: 'father with his hat off' },
  { t: 85,  text: 'kitchen radio low' },
  { t: 92,  text: 'we counted summer fireflies' },
  { t: 99,  text: 'and let the river go' },
  { t: 108, text: '' },
  { t: 113, text: '[Chorus]' },
  { t: 115, text: 'carry me home, carry me home' },
  { t: 122, text: 'down the long red road' },
  { t: 129, text: 'porchlight burning, porchlight burning' },
  { t: 137, text: 'wherever you go' },
  { t: 148, text: '' },
  { t: 155, text: '[Outro]' },
  { t: 158, text: 'porchlight, porchlight' },
  { t: 167, text: 'Alabama, Alabama' },
  { t: 178, text: 'carry me home' },
];

export const LYRICS_PAPER_RINGS: TimedLyricLine[] = [
  { t: 0,   text: '[Verse]' },
  { t: 4,   text: 'paper rings on the dresser' },
  { t: 9,   text: 'glass teeth on the floor' },
  { t: 14,  text: "you said you'd be here, sweeter" },
  { t: 19,  text: 'the second time, the more' },
  { t: 25,  text: '' },
  { t: 28,  text: '[Chorus]' },
  { t: 30,  text: 'but the morning came in cheap' },
  { t: 35,  text: 'and the morning kept on cheap' },
  { t: 41,  text: 'paper rings, paper rings' },
  { t: 47,  text: 'I am too tired to keep' },
  { t: 55,  text: '' },
  { t: 60,  text: '[Verse]' },
  { t: 63,  text: 'found a tooth in the carpet' },
  { t: 68,  text: 'found your handwriting in pen' },
  { t: 73,  text: "you wrote 'sorry' like a question" },
  { t: 78,  text: 'and erased it again' },
  { t: 86,  text: '' },
  { t: 92,  text: '[Outro]' },
  { t: 96,  text: 'paper rings / glass teeth' },
  { t: 105, text: 'paper rings / glass teeth' },
  { t: 115, text: 'paper rings' },
];

export const LYRICS_BY_ID: Record<string, TimedLyricLine[]> = {
  t01: LYRICS_LANTERN,
  t03: LYRICS_PAPER_KITES,
  t07: LYRICS_PORCHLIGHT,
  t11: LYRICS_PAPER_RINGS,
};
